name: Telegram Notifications

on:
  push:
    branches:
      - main  # Замените на вашу основную ветку

  release:
    types: [created]

jobs:
  send_telegram_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.event_name == 'push' && 'Новый коммит в репозитории [' + github.repository + '](' + github.event.repository.html_url + ') на ветке ' + github.ref  || 'Новый релиз ' + github.event.release.tag_name + ' в репозитории [' + github.repository + '](' + github.event.repository.html_url + ')' }}

            ${{ github.event_name == 'push' && 'Сообщение коммита:\n' + github.event.head_commit.message  || '' }}

            ${{ github.event_name == 'push' && 'Автор: ' + github.actor  || '' }}

            ${{ github.event_name == 'push' && 'Посмотреть коммит: ' + github.event.head_commit.url  || 'Посмотреть релиз: ' + github.event.release.html_url }}

            #${{ github.event_name == 'push' && 'github #commit' || 'github #release' }}