name: Notify Telegram

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Отправка уведомления о новом коммите
        if: github.event_name == 'push'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="Новый коммит в репозитории ${{ github.repository }} на ветке ${{ github.ref }}.\nСообщение коммита: ${{ github.event.head_commit.message }}\nАвтор: ${{ github.event.head_commit.author.name }}"

      - name: Отправка уведомления о новом релизе
        if: github.event_name == 'release'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="Новый релиз в репозитории ${{ github.repository }}.\nНазвание релиза: ${{ github.event.release.name }}\nОписание: ${{ github.event.release.body }}\nURL: ${{ github.event.release.html_url }}"
